// import { generateBoxShadowStyle } from "utils/generateShadow";

const { StyleSheet } = require("react-native");

export const styles = StyleSheet.create({
  mainContainer: {
    height: "100%",
    overflow: "scroll",
    width: "100%",
  },
  container: {
    padding: 10,
  },
  Card: {
    marginTop: 15,
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    height: 140,
    padding: 20,
    flexDirection: "column",
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  CardTitle: {
    flexDirection: "row",
    alignItems: "center",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardDetail: {
    flexDirection: "row",
    marginTop: 10,
    justifyContent: "space-between",
  },
  eachItem: {
    alignItems: "center",
    marginRight: 10,
  },
  itemHead: {
    fontSize: 10,
    fontWeight: "500",
  },
  itemValueContainer: {
    borderRadius: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 7,
    paddingRight: 7,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 50,
  },
  itemValue: {
    fontSize: 12,
    fontWeight: "700",
    color: "#272727",
  },
  CardHead: {
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 10,
  },
  SelectorBar: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  WhiteText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#fff",
  },
  DetailContainer: {
    flexDirection: "row",
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    height: 130,
    padding: 20,
  },
  tableRow: {
    flexDirection: "row",
    width: "100%",
    marginBottom: 5,
    justifyContent: "space-between",
  },
  tableTitle: {
    color: "#a3a3a3",
    fontSize: 12,
    fontWeight: "400",
    width: "30%",
  },
  tableValue: {
    color: "#1f1e1e",
    fontSize: 12,
    fontWeight: "500",
    width: "70%",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  ExamsContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
  },
  eachExam: {
    borderColor: "#fff",
    borderWidth: 1,
    padding: 4,
    paddingLeft: 8,
    paddingRight: 8,
    marginRight: 10,
  },
  examTitle: {
    fontSize: 10,
    fontWeight: "400",
    color: "#fff",
  },
  reportCard: {
    alignItems: "center",
    marginTop: 15,
  },
  reportRow: {
    flexDirection: "row",
    marginBottom: 10,
  },
  whiteCard: {
    backgroundColor: "#f9fafe",
    borderWidth: 1,
    borderColor: "#d0d0d0",
    marginTop: 10,
    padding: 10,
    borderRadius: 10,
    width: "100%",
  },
  reportCell: {
    alignItems: "center",
    justifyContent: "center",
    width: "25%",
  },
  cellBg: {
    backgroundColor: "#eaeaea",
    padding: 4,
    width: 45,
    height: 33,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },
  cellValue: {
    fontSize: 14,
    fontWeight: "500",
  },
  reportTile: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  AttendanceContainer: {
    width: "100%",
    minHeight: 100,
    borderRadius: 5,
    backgroundColor: "#fff",
    marginTop: 15,
    paddingTop: 15,
    paddingBottom: 15,
  },
  cell: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#dbdbdb",
    minWidth: 90,
    justifyContent: "center",
    alignItems: "center",
  },
  tableHead: {
    fontSize: 12,
    color: "#222222",
    fontWeight: "500",
  },
  presentContainer: {
    backgroundColor: "#9ce2c9",
    borderRadius: 6,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    flexDirection: "column",
    gap: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  absentContainer: {
    backgroundColor: "#ffa7a8",
    borderRadius: 6,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
  },
});
