export const WHO_AM_I_START = "WHO_AM_I_START";
export const WHO_AM_I_SUCCESS = "WHO_AM_I_SUCCESS";
export const WHO_AM_I_REFRESH_SUCCESS = "WHO_AM_I_REFRESH_SUCCESS";
export const WHO_AM_I_FAILURE = "WHO_AM_I_FAILURE";

export const GET_OTP_START = "GET_OTP_START";
export const GET_OTP_SUCCESS = "GET_OTP_SUCCESS";
export const GET_OTP_FAILURE = "GET_OTP_FAILURE";

export const VERIFY_OTP_START = "VERIFY_OTP_START";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_TOKEN_START = "GET_TOKEN_START";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_STUDENT_LIST_START = "GET_STUDENT_LIST_START";
export const GET_STUDENT_LIST_SUCCESS = "GET_STUDENT_LIST_SUCCESS";
export const GET_STUDENT_LIST_FAILURE = "GET_STUDENT_LIST_FAILURE";

export const SET_STUDENT_PREFERENCE_START = "SET_STUDENT_PREFERENCE_START";
export const SET_STUDENT_PREFERENCE_SUCCESS = "SET_STUDENT_PREFERENCE_SUCCESS";
export const SET_STUDENT_PREFERENCE_FAILURE = "SET_STUDENT_PREFERENCE_FAILURE";

export const GET_STUDENT_DETAILS_START = "GET_STUDENT_DETAILS_START";
export const GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS";
export const GET_STUDENT_DETAILS_FAILURE = "GET_STUDENT_DETAILS_FAILURE";

export const GET_STUDENT_ATTENDANCE_STATS_START =
  "GET_STUDENT_ATTENDANCE_STATS_START";
export const GET_STUDENT_ATTENDANCE_STATS_SUCCESS =
  "GET_STUDENT_ATTENDANCE_STATS_SUCCESS";
export const GET_STUDENT_ATTENDANCE_STATS_FAILURE =
  "GET_STUDENT_ATTENDANCE_STATS_FAILURE";

export const GET_STUDENT_EXAM_STATS_START = "GET_STUDENT_EXAM_STATS_START";
export const GET_STUDENT_EXAM_STATS_SUCCESS = "GET_STUDENT_EXAM_STATS_SUCCESS";
export const GET_STUDENT_EXAM_STATS_FAILURE = "GET_STUDENT_EXAM_STATS_FAILURE";

export const GET_SECTION_TIMETABLE_START = "GET_SECTION_TIMETABLE_START";
export const GET_SECTION_TIMETABLE_SUCCESS = "GET_SECTION_TIMETABLE_SUCCESS";
export const GET_SECTION_TIMETABLE_FAILURE = "GET_SECTION_TIMETABLE_FAILURE";

export const GET_STUDENT_INDIVIDUAL_ATTENDANCE_START =
  "GET_STUDENT_INDIVIDUAL_ATTENDANCE_START";
export const GET_STUDENT_INDIVIDUAL_ATTENDANCE_SUCCESS =
  "GET_STUDENT_INDIVIDUAL_ATTENDANCE_SUCCESS";
export const GET_STUDENT_INDIVIDUAL_ATTENDANCE_FAILURE =
  "GET_STUDENT_INDIVIDUAL_ATTENDANCE_FAILURE";

export const GET_ACTIVITY_SUMMARY_START = "GET_ACTIVITY_SUMMARY_START";
export const GET_ACTIVITY_SUMMARY_SUCCESS = "GET_ACTIVITY_SUMMARY_SUCCESS";
export const GET_ACTIVITY_SUMMARY_FAILURE = "GET_ACTIVITY_SUMMARY_FAILURE";

export const GET_STUDENT_TIME_OFF_START = "GET_STUDENT_TIME_OFF_START";
export const GET_STUDENT_TIME_OFF_SUCCESS = "GET_STUDENT_TIME_OFF_SUCCESS";
export const GET_STUDENT_TIME_OFF_FAILURE = "GET_STUDENT_TIME_OFF_FAILURE";

export const GET_COMMUNICATION_CATEGORY_START =
  "GET_COMMUNICATION_CATEGORY_START";
export const GET_COMMUNICATION_CATEGORY_SUCCESS =
  "GET_COMMUNICATION_CATEGORY_SUCCESS";
export const GET_COMMUNICATION_CATEGORY_FAILURE =
  "GET_COMMUNICATION_CATEGORY_FAILURE";

export const GET_STUDENT_LEAVE_APPLY_START = "GET_STUDENT_LEAVE_APPLY_START";
export const GET_STUDENT_LEAVE_APPLY_SUCCESS =
  "GET_STUDENT_LEAVE_APPLY_SUCCESS";
export const GET_STUDENT_LEAVE_APPLY_FAILURE =
  "GET_STUDENT_LEAVE_APPLY_FAILURE";

export const CREATE_STUDENT_LEAVE_APPLY_START =
  "CREATE_STUDENT_LEAVE_APPLY_START";
export const CREATE_STUDENT_LEAVE_APPLY_SUCCESS =
  "CREATE_STUDENT_LEAVE_APPLY_SUCCESS";
export const CREATE_STUDENT_LEAVE_APPLY_FAILURE =
  "CREATE_STUDENT_LEAVE_APPLY_FAILURE";

export const UPDATE_STUDENT_LEAVE_APPLY_START =
  "UPDATE_STUDENT_LEAVE_APPLY_START";
export const UPDATE_STUDENT_LEAVE_APPLY_SUCCESS =
  "UPDATE_STUDENT_LEAVE_APPLY_SUCCESS";
export const UPDATE_STUDENT_LEAVE_APPLY_FAILURE =
  "UPDATE_STUDENT_LEAVE_APPLY_FAILURE";

export const DELETE_STUDENT_LEAVE_APPLY_START =
  "DELETE_STUDENT_LEAVE_APPLY_START";
export const DELETE_STUDENT_LEAVE_APPLY_SUCCESS =
  "DELETE_STUDENT_LEAVE_APPLY_SUCCESS";
export const DELETE_STUDENT_LEAVE_APPLY_FAILURE =
  "DELETE_STUDENT_LEAVE_APPLY_FAILURE";

export const GET_TICKET_START = "GET_TICKET_START";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAILURE = "GET_TICKET_FAILURE";

export const CREATE_TICKET_START = "CREATE_TICKET_START";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAILURE = "CREATE_TICKET_FAILURE";

export const GET_ONE_TICKET_INFO_START = "GET_ONE_TICKET_INFO_START";
export const GET_ONE_TICKET_INFO_SUCCESS = "GET_ONE_TICKET_INFO_SUCCESS";
export const GET_ONE_TICKET_INFO_FAILURE = "GET_ONE_TICKET_INFO_FAILURE";

export const ADD_MESSAGE_TO_TICKET_START = "ADD_MESSAGE_TO_TICKET_START";
export const ADD_MESSAGE_TO_TICKET_SUCCESS = "ADD_MESSAGE_TO_TICKET_SUCCESS";
export const ADD_MESSAGE_TO_TICKET_FAILURE = "ADD_MESSAGE_TO_TICKET_FAILURE";

export const GET_EXAM_ROSTER_START = "GET_EXAM_ROSTER_START";
export const GET_EXAM_ROSTER_SUCCESS = "GET_EXAM_ROSTER_SUCCESS";
export const GET_EXAM_ROSTER_FAILURE = "GET_EXAM_ROSTER_FAILURE";

export const GET_ONE_EXAM_DATA_START = "GET_ONE_EXAM_DATA_START";
export const GET_ONE_EXAM_DATA_SUCCESS = "GET_ONE_EXAM_DATA_SUCCESS";
export const GET_ONE_EXAM_DATA_FAILURE = "GET_ONE_EXAM_DATA_FAILURE";

export const GET_SECTION_COURSE_DETAILS_START =
  "GET_SECTION_COURSE_DETAILS_START";
export const GET_SECTION_COURSE_DETAILS_SUCCESS =
  "GET_SECTION_COURSE_DETAILS_SUCCESS";
export const GET_SECTION_COURSE_DETAILS_FAILURE =
  "GET_SECTION_COURSE_DETAILS_FAILURE";

export const SET_NOTIFICATION_TOKEN_START = "SET_NOTIFICATION_TOKEN_START";
export const SET_NOTIFICATION_TOKEN_SUCCESS = "SET_NOTIFICATION_TOKEN_SUCCESS";
export const SET_NOTIFICATION_TOKEN_FAILURE = "SET_NOTIFICATION_TOKEN_FAILURE";

/* Attendance Status */
export const GET_ATTENDANCE_STATUS_START = "GET_ATTENDANCE_STATUS_START";
export const GET_ATTENDANCE_STATUS_SUCCESS = "GET_ATTENDANCE_STATUS_SUCCESS";
export const GET_ATTENDANCE_STATUS_FAILURE = "GET_ATTENDANCE_STATUS_FAILURE";

export const GET_ALL_EVENTS_START = "GET_ALL_EVENTS_START";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const GET_NOTIFICATION_START = "GET_NOTIFICATION_START";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE";

export const UPDATE_NOTIFICATION_START = "UPDATE_NOTIFICATION_START";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_FAILURE = "UPDATE_NOTIFICATION_FAILURE";

export const GET_NOTIFICATION_SETTINGS_START =
  "GET_NOTIFICATION_SETTINGS_START";
export const GET_NOTIFICATION_SETTINGS_SUCCESS =
  "GET_NOTIFICATION_SETTINGS_SUCCESS";
export const GET_NOTIFICATION_SETTINGS_FAILURE =
  "GET_NOTIFICATION_SETTINGS_FAILURE";

export const UPDATE_NOTIFICATION_SETTINGS_START =
  "UPDATE_NOTIFICATION_SETTINGS_START";
export const UPDATE_NOTIFICATION_SETTINGS_SUCCESS =
  "UPDATE_NOTIFICATION_SETTINGS_SUCCESS";
export const UPDATE_NOTIFICATION_SETTINGS_FAILURE =
  "UPDATE_NOTIFICATION_SETTINGS_FAILURE";

export const CHANGE_STUDENT_PAGE_CARD_VIEW = "CHANGE_STUDENT_PAGE_CARD_VIEW";

export const CHANGE_STATE = "CHANGE_STATE";
