const { StyleSheet } = require("react-native");

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    flexDirection: "column",
    height: "100%",
    padding: 0,
    backgroundColor: "#03A07A",
  },
  background: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 300,
  },
  Wrapper: {
    height: "100%",
  },
  BigCard: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    minHeight: 405,
    maxHeight: 405,
    padding: 10,
    flexDirection: "column",
  },
  CardHead: {
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 10,
  },
  InnerCard: {
    width: "100%",
    marginTop: 10,
    height: 80,
    borderWidth: 1,
    borderColor: "#e1e3e8",
    borderRadius: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
  },
  leftCard: {
    height: "100%",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  rightCard: {
    height: "100%",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  bold: {
    fontWeight: "600",
    color: "#313131",
  },
  Card: {
    marginTop: 15,
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    height: 130,
    padding: 20,
    flexDirection: "column",
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardDetail: {
    flexDirection: "row",
    marginTop: 10,
    justifyContent: "space-between",
  },
  eachItem: {
    alignItems: "center",
    marginRight: 10,
  },
  itemHead: {
    fontSize: 10,
    fontWeight: "500",
  },
  itemValueContainer: {
    borderRadius: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 7,
    paddingRight: 7,
    justifyContent: "center",
    alignItems: "center",
  },
  itemValue: {
    fontSize: 12,
    fontWeight: "700",
    color: "#272727",
  },
  feesCard: {
    backgroundColor: "#edfffb",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
    marginTop: 15,
    marginBottom: 30,
  },
  button: {
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
    width: 154,
    height: 44,
    marginTop: 5,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "500",
  },
  quickButtons: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginTop: 15,
  },
  CardTitle: {
    flexDirection: "row",
    alignItems: "center",
  },
  eachQuickButton: {
    alignItems: "center",
  },
  quickButtonText: {
    fontSize: 10,
    fontWeight: "500",
    color: "#2c3134",
    marginTop: 5,
  },
  card: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    minHeight: 225,
    maxHeight: 205,
    flexDirection: "column",
    padding: 10,
  },
});
